version: '2'
services:
  # Refers to https://github.com/fuadajip/dockercompose-mysql-phpmyadmin
  blog-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # links:
    #   - blog-mariadb
    ports:
      - '7777:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=blog-mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=
    restart: always
